"""
Django settings for converter project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from converter.settings import *  # noqa

SECRET_KEY = 'django-insecure-n)b&o&!3!8jhuqq!kii#5jv#aq-pu@$o7bcrpalipn4)$u)_#a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", "0.0.0.0"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"level": "INFO", "class": "logging.StreamHandler",},  # noqa
    },  # noqa
    "loggers": {
        "": {"handlers": ["console"], "level": "INFO", "propagate": True,},  # noqa
    },  # noqa
}
